//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auxiliar
    {
        public auxiliar()
        {
            this.hojaRutaDetalles = new HashSet<hojaRutaDetalle>();
        }
    
        public int run { get; set; }
        public string rut { get; set; }
        public string nombreRazonSocial { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
    
        public virtual ICollection<hojaRutaDetalle> hojaRutaDetalles { get; set; }
    }
}
