//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadoEntrega
    {
        public estadoEntrega()
        {
            this.hojaRutaDetalleGuia = new HashSet<hojaRutaDetalleGuia>();
        }
    
        public int idEstadoEntrega { get; set; }
        public string descEstadoEntrega { get; set; }
    
        public virtual ICollection<hojaRutaDetalleGuia> hojaRutaDetalleGuia { get; set; }
    }
}
