//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hojaRutaDetalleGuia
    {
        public int idHrdGuia { get; set; }
        public int idHojaRutaDetalle { get; set; }
        public int numeroGuia { get; set; }
        public int idEstadoEntrega { get; set; }
        public string observaciones { get; set; }
    
        public virtual estadoEntrega estadoEntrega { get; set; }
        public virtual guia guia { get; set; }
        public virtual hojaRutaDetalle hojaRutaDetalle { get; set; }
    }
}
