//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hojaRuta
    {
        public hojaRuta()
        {
            this.colaboradorHojaRuta = new HashSet<colaboradorHojaRuta>();
            this.costosHojaRuta = new HashSet<costosHojaRuta>();
            this.hojaRutaDetalle = new HashSet<hojaRutaDetalle>();
        }
    
        public int idHojaRuta { get; set; }
        public string idVehiculo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<colaboradorHojaRuta> colaboradorHojaRuta { get; set; }
        public virtual ICollection<costosHojaRuta> costosHojaRuta { get; set; }
        public virtual estadoHojaRuta estadoHojaRuta { get; set; }
        public virtual fechaTramo fechaTramo { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        public virtual ICollection<hojaRutaDetalle> hojaRutaDetalle { get; set; }
    }
}
