//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hojaRutaDetalle
    {
        public hojaRutaDetalle()
        {
            this.hojaRutaDetalleGuia = new HashSet<hojaRutaDetalleGuia>();
        }
    
        public int idHojaRutaDetalle { get; set; }
        public int idHojaRuta { get; set; }
        public int idCliente { get; set; }
        public int numeroGuia { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> fechaLlegada { get; set; }
    
        public virtual auxiliar auxiliar { get; set; }
        public virtual hojaRuta hojaRuta { get; set; }
        public virtual ICollection<hojaRutaDetalleGuia> hojaRutaDetalleGuia { get; set; }
    }
}
