//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dimacodevEntities1 : DbContext
    {
        public dimacodevEntities1()
            : base("name=dimacodevEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<auxiliar> auxiliar { get; set; }
        public DbSet<colaborador> colaborador { get; set; }
        public DbSet<colaboradorHojaRuta> colaboradorHojaRuta { get; set; }
        public DbSet<costosHojaRuta> costosHojaRuta { get; set; }
        public DbSet<estadoEntrega> estadoEntrega { get; set; }
        public DbSet<estadoHojaRuta> estadoHojaRuta { get; set; }
        public DbSet<fechaTramo> fechaTramo { get; set; }
        public DbSet<guias> guias { get; set; }
        public DbSet<hojaRuta> hojaRuta { get; set; }
        public DbSet<hojaRutaDetalle> hojaRutaDetalle { get; set; }
        public DbSet<hojaRutaDetalleGuia> hojaRutaDetalleGuia { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
