//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlantilla.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dimacodevEntities : DbContext
    {
        public dimacodevEntities()
            : base("name=dimacodevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<auxiliar> auxiliars { get; set; }
        public DbSet<colaborador> colaboradors { get; set; }
        public DbSet<colaboradorHojaRuta> colaboradorHojaRutas { get; set; }
        public DbSet<costosHojaRuta> costosHojaRutas { get; set; }
        public DbSet<estadoEntrega> estadoEntregas { get; set; }
        public DbSet<estadoHojaRuta> estadoHojaRutas { get; set; }
        public DbSet<fechaTramo> fechaTramoes { get; set; }
        public DbSet<guia> guias { get; set; }
        public DbSet<hojaRuta> hojaRutas { get; set; }
        public DbSet<hojaRutaDetalle> hojaRutaDetalles { get; set; }
        public DbSet<hojaRutaDetalleGuia> hojaRutaDetalleGuias { get; set; }
        public DbSet<vehiculo> vehiculoes { get; set; }
    }
}
